### PR TITLE
Corrected license

### PR DESCRIPTION
**Pull request by pfefferle**
;)

### CODE REVIEW

**Comment by dshanske** [comment]
I thought I copied over the GPLv2 license. Must have overwritten when I copied over some of the webmention files.

**Comment by dshanske** [comment]
Oh well, I did this in an hour.

**Comment by dshanske** [comment]
@pfefferle Should I take these PRs as an endorsement of the plugin?

**Comment by pfefferle** [comment]
sure, like the idea... if you have a packagist account I will add you to the project: https://packagist.org/packages/dshanske/wordpress-refback/

**Pull request merged**
